// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4KLzG5GurVprM4yIcaMvP3LyjQ_56i6w',
    appId: '1:132684119931:web:54d2c5d8a61a2404ed87de',
    messagingSenderId: '132684119931',
    projectId: 'warwick-society-app',
    authDomain: 'warwick-society-app.firebaseapp.com',
    storageBucket: 'warwick-society-app.appspot.com',
    measurementId: 'G-F57NJKSL37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-UllX23JJ8mY8NbdULJ8L-TpeoAhfdA',
    appId: '1:132684119931:android:94b6f081a8be34f9ed87de',
    messagingSenderId: '132684119931',
    projectId: 'warwick-society-app',
    storageBucket: 'warwick-society-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8zqjWOddt6b-2XKhPpA7sl3Cbj5QWMQ',
    appId: '1:132684119931:ios:72b5ba456abd1ebaed87de',
    messagingSenderId: '132684119931',
    projectId: 'warwick-society-app',
    storageBucket: 'warwick-society-app.appspot.com',
    iosClientId: '132684119931-66fu5m0n3koal506nr63uhlmf9qrmeg4.apps.googleusercontent.com',
    iosBundleId: 'com.socs.warwicksocietyapp',
  );
}
